config/routes.rb
Stori::Application.routes.draw do

  root :to => 'story_threads#index'

  resources :story_posts, :only => [:create]

  resources :story_threads, :only => [:show]

end

app/models/story_post.rb
class StoryPost < ActiveRecord::Base
  LAST_WORD_AMOUNT = 3

  attr_accessible :story_thread, :text, :parent_id

  belongs_to :story_thread

  validates :text, :length => { :maximum => 140, :minimum => 1 }

  def parent_id=(parent_id)
    self[:parent_id] = parent_id
  end

  def last_words
    last_words = text.split(" ").last(LAST_WORD_AMOUNT)
    return last_words.join(" ")
  end
end

app/models/story_thread.rb
class StoryThread < ActiveRecord::Base
  attr_accessible :end, :name, :start

  has_many :story_posts

  scope :finished, lambda { where('end_time < ?', DateTime.now).order('end_time DESC') }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/story_posts_controller.rb
class StoryPostsController < ApplicationController

  # GET /story_posts/new
  # GET /story_posts/new.json
  def new
    @story_post = StoryPost.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @story_post }
    end
  end

  # POST /story_posts
  # POST /story_posts.json
  def create
    @story_post = StoryPost.new(params[:story_post])
    @story_post.text.strip!
    @story_post.story_thread = StoryThreadsController.current_thread

    respond_to do |format|
      if correct_parent?(@story_post)
        if @story_post.save
          format.html { redirect_to root_path, notice: 'Story post was successfully created.' }
        else
          format.html { redirect_to root_path, notice: 'Error when trying to save post.' }
        end
      else
        format.html { redirect_to root_path, notice: 'Somebody else posted before you.' }
      end
    end
  end

  def correct_parent? story_post
    current_parent_id = StoryThreadsController.current_thread.story_posts.last.id
    given_parent_id = story_post.parent_id.to_i
    return current_parent_id == given_parent_id
  end
end

app/controllers/story_threads_controller.rb
class StoryThreadsController < ApplicationController
  NEW_DAY_START = 5.hours

  # GET /story_threads
  # GET /story_threads.json
  def index
    previous_post = StoryThreadsController.current_thread.story_posts.last
    @last_words = previous_post.last_words
    @parent_id = previous_post.id
    @finished_threads = StoryThread.finished
    @story_post = StoryPost.new

    respond_to do |format|
      format.html # index.html.erb
    end
  end

  # GET /story_threads/1
  # GET /story_threads/1.json
  def show
    @story_thread = StoryThread.find(params[:id])

    respond_to do |format|
      if (@story_thread.end_time.future?)
        format.html { redirect_to root_path, notice: 'Thread is not finished and cannot be viewed.' }
      else
        format.html # show.html.erb
      end
    end
  end

  def self.current_thread
    current_last = StoryThread.last
    if current_last.nil? || current_last.end_time.past?
      current_last = create_new_thread
    end
    return current_last
  end

  def self.create_new_thread
    new_day_midnight = DateTime.now.beginning_of_day
    new_start = new_day_midnight + 5.hours
    new_end = new_start + 1.day
    new_name = new_start.to_date.to_s

    story_thread = StoryThread.new
    story_thread.start_time = new_start
    story_thread.end_time = new_end
    story_thread.name = new_name
    add_default_post story_thread

    if story_thread.save
      return story_thread
    else
      return nil
    end
  end

  def self.add_default_post(story_thread)
    default = StoryPost.new
    default.text = "Idag har jag"
    default.story_thread = story_thread

    if default.save
      return default
    else
      return nil
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/story_posts_helper.rb
module StoryPostsHelper
end

app/helpers/story_threads_helper.rb
module StoryThreadsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Stori</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<div id="container">
  <%= yield %>
</div>

</body>
</html>

app/views/story_posts/_form.html.erb
<%= form_for(@story_post) do |f| %>
  <% if @story_post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@story_post.errors.count, "error") %> prohibited this story_post from being saved:</h2>

      <ul>
      <% @story_post.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :text %><br />
    <%= f.text_field :text %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/story_posts/edit.html.erb
<h1>Editing story_post</h1>

<%= render 'form' %>

<%= link_to 'Show', @story_post %> |
<%= link_to 'Back', story_posts_path %>

app/views/story_posts/index.html.erb
<%= javascript_include_tag "application", :debug => true %>

<h1>Listing story_posts</h1>

<br />

<%= link_to 'New Story post', new_story_post_path %>

app/views/story_posts/new.html.erb
<h1>New story_post</h1>

<%= render 'form' %>

<%= link_to 'Back', story_posts_path %>

app/views/story_posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Text:</b>
  <%= @story_post.text %>
</p>

<p>
  <b>Story thread:</b>
  <%= @story_post.story_thread %>
</p>


<%= link_to 'Edit', edit_story_post_path(@story_post) %> |
<%= link_to 'Back', story_posts_path %>

app/views/story_threads/_form.html.erb
<%= form_for(@story_thread) do |f| %>
  <% if @story_thread.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@story_thread.errors.count, "error") %> prohibited this story_thread from being saved:</h2>

      <ul>
      <% @story_thread.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :start %><br />
    <%= f.datetime_select :start %>
  </div>
  <div class="field">
    <%= f.label :end %><br />
    <%= f.datetime_select :end %>
  </div>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/story_threads/edit.html.erb
<h1>Editing story_thread</h1>

<%= render 'form' %>

<%= link_to 'Show', @story_thread %> |
<%= link_to 'Back', story_threads_path %>

app/views/story_threads/index.html.erb
<h1 class="animated bounceInRight">CONTINUE THE STORI</h1>
<hr class="animated bounceInRight">

<% if flash[:notice] %>
  <div class="notice animated bounceInRight"><%= flash[:notice] %></div>
<% end %>
<p id="words" class="animated bounceInLeft"><span class="dots">... </span><%= @last_words %><span class="dots">...</span></p>

<%= form_for @story_post, :html => { :class => "animated bounceInRight" } do |f| %>
  <%= f.text_area :text, id: "input-area", maxlength: "140" %><br />
  <%= f.hidden_field "parent_id", value: @parent_id %>
  <div id="counter">140</div>
  <%= f.submit %>
<% end %>

<h1 id="finished-title" class="animated bounceInLeft">FINISHED STORIS</h1>
<div id="finished-list">
  <% @finished_threads.each_with_index do |finished_thread, i| %>
    <!-- here there be dragons -->
    <% animated_class = i.odd? ? "animated bounceInRight" : "animated bounceInLeft" %>
    <% delay = 1.2 + 0.2*i %>
    <% delay_css = "-webkit-animation-delay: #{delay}s; -moz-animation-delay: #{delay}s;" %>
    <%= link_to finished_thread.name, story_thread_path(finished_thread), class: animated_class, style: delay_css %>
  <% end %>
</div>

app/views/story_threads/new.html.erb
<h1>New story_thread</h1>

<%= render 'form' %>

<%= link_to 'Back', story_threads_path %>

app/views/story_threads/show.html.erb
<p id="notice"><%= notice %></p>

<h1>
  <%= @story_thread.name %>
</h1>

<p id="stori">
<% @story_thread.story_posts.each do |story_post| %> <%="#{story_post.text} "%> <% end %>
</p>

<%= link_to "Back to main page", root_path %>